export interface ParsedArgs {
  command: string;
  url?: string;
  name?: string | null;
  dict?: string | null;
  port?: number;
  transcript_dir?: string | null;
  rtmp_url?: string | null;
  rtmp?: boolean;
  ws_video?: boolean;
  webhook_base?: string | null;
  tunnel?: string | null;
  no_presence?: boolean;
  presence_bg?: string | null;
  frame_dir?: string | null;
  variant?: string | null;
  bot_id?: string | null;
  chime?: string | null;
  list_chimes?: boolean;
  transcript_cursor?: number;
  transcript_limit?: number;
  transcript_local?: boolean;
  out?: string | null;
  archive?: boolean;
  frame_source?: string | null;
  message?: string;
  transcript_file?: string;
  webhook_token?: string;
  call_id_file?: string;
  public_base?: string;
  frame_token?: string;
  presence_token?: string;
  presence_write_token?: string;
  presence_state?: string;
  doc_id?: string | null;
  credentials?: string | null;
  from_start?: boolean;
  notes_action?: string;
  section?: string | null;
  speaker?: string | null;
  owner?: string | null;
  due?: string | null;
  title?: string | null;
  intro?: boolean;
  intro_text?: string | null;
  context?: boolean;
  agent_action?: "connect" | "context" | "chat" | "disconnect";
  agent_binding_id?: string;
  agent_call_id?: string;
  agent_provider?: "codex" | "claude-code" | "other";
  agent_session_id?: string;
  agent_origin?: string;
  agent_credential_file?: string;
  agent_after_seq?: number;
  agent_request_id?: string;
  agent_allow_loopback_http?: boolean;
}
