export interface ParsedArgs {
  command: string;
  url?: string;
  name?: string | null;
  dict?: string | null;
  port?: number;
  transcript_dir?: string | null;
  rtmp_url?: string | null;
  rtmp?: boolean;
  ws_video?: boolean;
  webhook_base?: string | null;
  frame_dir?: string | null;
  bot_id?: string | null;
  transcript_cursor?: number;
  transcript_limit?: number;
  transcript_local?: boolean;
  out?: string | null;
  archive?: boolean;
  message?: string;
  transcript_file?: string;
  webhook_token?: string;
  call_id_file?: string;
  frame_token?: string;
  doc_id?: string | null;
  credentials?: string | null;
  from_start?: boolean;
  notes_action?: string;
  section?: string | null;
  speaker?: string | null;
  owner?: string | null;
  due?: string | null;
  title?: string | null;
}
