// AUTO-GENERATED soft chime library. Do not edit by hand; regenerate with
// scripts/gen-chimes.sh (requires ffmpeg + libmp3lame).
//
// Each value is a short (~0.2-0.4s), low-gain MP3 chime, base64-encoded and
// inlined so samograph ships no binary asset files. These are played into the
// call's audio track via Recall's output_audio endpoint when the bot posts a
// meeting-chat message -- the AUDIBLE path participants hear. The camera-page
// WebAudio cue in presence.ts is a separate, video-only nicety.
//
// Generated offline with ffmpeg (libmp3lame, mono, 44.1 kHz, 48 kbps) from
// synthesized sine tones / sweeps.
//
// Sounds (all soft, non-annoying):
//   blip     soft rising glide 540->680 Hz (legacy default)
//   two-tone two gentle pips, 660 then 880 Hz
//   rising   smooth upward sweep 440->880 Hz
//   falling  smooth downward sweep 880->440 Hz
//   bell     soft bell: fundamental + octave partial, exp decay
//   marimba  woody pluck around 587 Hz, fast decay
//   glass    high glassy ping around 1175 Hz
//   pop      very short soft pop around 420 Hz
//   chord    soft two-note chord (C5 + E5)
//   pulse    gentle double-pulse at 700 Hz

export const DEFAULT_CHIME = "blip";

// name -> base64-encoded MP3 (mono). DEFAULT_CHIME must be a key here.
export const CHIME_LIBRARY: Record<string, string> = {
  "blip":
    "SUQzBAAAAAAAIlRTU0UAAAAOAAADTGF2ZjYxLjEuMTAwAAAAAAAAAAAAAAD/+0DAAAAAAAAAAAAAAAAAAAAAAABJbmZvAAAADwAA" +
    "AA0AAAirACYmJiYmJiY5OTk5OTk5OUtLS0tLS0tLXV1dXV1dXW9vb29vb29vgYGBgYGBgYGTk5OTk5OTpaWlpaWlpaW3t7e3t7e3" +
    "t8nJycnJycnb29vb29vb2+7u7u7u7u7u/////////wAAAABMYXZjNjEuMy4AAAAAAAAAAAAAAAAkBJIAAAAAAAAIq2WsPFIAAAAA" +
    "AP/7MMQAAAdcQQYVt4AJCwqkwzxQADAxkztfN5hTf18yEgN0tD3u49qcMsMTrs48qoN8UDKgptYaBgEYMEAoEDnFvEPFzJ2aaHq9" +
    "nePHjygAgAMCMMUsuYIgBggAcMAAEsybx6TDgAMMwxLIyFwazP1djM9wZALAANxCoA7oGBUASTADiRsAwcyl4cBxD/FBB8oTSm4o" +
    "6GAqBEYF4P/7MsQEg8dwKR4d5IAI64VhAc/slHhgSgRmEYHeYyRVJotNEm+2+UYpAUZkkCvmFMDaYKgC5gEgHIpJJLCsNA0TAoKC" +
    "m9FfwwKCjAQVMDiYwgRTE5+MtQUwOMKoMJyLqzTxudU1ndd/MKNDNjB2AI08EyNiFTNQIINSYSSQaRBMqO1VS8MLDzIiY0NJNwej" +
    "yeEwZ4IoMNRGAzEqERv/+zLEDQPHnC0IDf+EoR4GIIGv7Jg1/n8ONKYJiDIKgrw9+/zXByMwjsxwIjEYVMKA4wAAEU3ctlsQaCCg" +
    "8EojJRTx2jBpg4ow+ogiMlpFxjIh3M4+2ErzNmMG9jE7xC8wFQHuMAgBGTF6wUZTDDAFGhMfEwa59S6HAfBk0Fr9KnuUsCADMEAA" +
    "MKwDMZBtOZYVN/qPNsjlMj+5MvUa//syxA6Dx7AtCA7/aEECBeBB3/EN9T64iSIwSEaaMQKA0zBaQFA6whCLIyIACgUOAq0pT/7p" +
    "OyRDcBAgYVhuYoC0dh6ccQoebDDeYgWeYc8P9G0u8rB6zOHGaoeKHmIrBWR7HCnAH8a7XZnc1mXhkYrBoYAMFKWaglRolPzNjc5P" +
    "GMYozOW47NuMGqA1TFTycQya+KaPwVeBTKHQL//7MMQTg8gUMQQN/6hBDgbgQb/tEA56HozhFExkEQwkDQwTCsCA8QAe4/f///9P" +
    "71NrRBp8ZyimwHQCyjC7IwK0GhMIiDdDIfR3Ix23+cNPjIVTGxBRwwWcInMD+BNDyJI91LPCZjdX0mX3Mkdi2Fv/9NX//fkAFGRI" +
    "YAIZikiGcyobAJp2EoGGMAyJlNLXIfFnG9G75E0xhF4X+P/7MsQUg8hgPQIOf6pBIgegQb/hUIANwaPk0ZB82ejg1OAsSHImAlTl" +
    "5IfldTfr/9/8PF2TEw4yolNCVzR441L7MBfCDjAURg8zGxdFP2GQ7TJ8xLQxDwEWMEKB4DAbgzsxBEAZMB/AQDB8sISXXg1uH5Bf" +
    "d//+tf//+Xq8KBIxYBMQNSVqMVtTAQATgwI0J7MHYG6jRp5OI6mt27P/+zLEEoPIlD0EDf/KYPWHoEHP5Yw1HEdTM3SBMzcb0wKB" +
    "JDDjARAwRgYBuJAGIVqaNYhup///3XoVnWCL9DQkMXgEywFjVI7O8FAxLkbOMJ5WUjwIVX8x5AbFMPWC8TAfgKYwGMALK6h6IiFV" +
    "raZDFDr///1E3Yi7SASBmGChkZaaEpG9zpggwKsYcWELABhGOwVU7KwzOJIMdB8w//syxBWDxsA9DA3/jCEAB9/Bv+2M2CgEES+T" +
    "BZFQ01n///3KHLgRhYMBDCxkxwuM1UTUIAwG8CTMBcFITMgXDQ7hhTnNXJGuTCmAtwZBSTH7YxRtMDQhgjCgQiIjE1Gj///9xxu7" +
    "xL+FggFFZlQIaaCnFD5gmIMEYr0F7GC2ihplwbXgfsyGomEbDOph+YJYeQSJtUoGfBOZHAAQNP/7MMQeg8iIPvwN/4xA7YfhAc/x" +
    "xBEBEELDqXv////1XuUb8LrQAGCwKYqJxiAeHpumcEOpgR4TGZD8ksmZsGLRiZgEccbOpl4eGKRCYUCBgkElt06H7sL////lqWuy" +
    "z5KUkBQ6ITGUSNMm475izSbQMFvBOjEXiZMzsqfrOMWSID8iSzT0djFwIzBUAl0u0u1rUZv/3SOlAdYWoP/7MsQiA8eIPvoOf64A" +
    "5AggQU/lyK4HC9gY60A9OAgJgwQUBdMOmGTTL7G3MxwsNlML5A5zA1gGowGkA/PzA2GjLJLwNbzq/eTwgaJnYaLnXBgYgZGC0DSY" +
    "bIvhjiQsn61QMYq4ghiTA2GBeBSYBABhaAIADLOMJb/D/+kHXAMQH+CsFQBswDQBiMCjA1zB5gTQyA1L+NpvQXTGtQ7/+zLEKwPG" +
    "WEMCAGPIgNmI3wEf6cgkwB0DmNflNuVEzJ63osWjcus5Vf960yBUAdD4eAaMDQAowcwOTD0B2Mq0fw2NsVz7XYOMnYFc/NtNNdzA" +
    "pw8gnN6MWYR2au6VAJTkAGMYxjGMYAc7UMuMpUiqIwDDAEAbMAEIICDUmikpyY0geh/QF1wqwKpizMPUVSwCYPg+D92JwI7+n8uD" +
    "//syxDoDBqBI9AB7ask2iOAMH2WS4E+CAIAgCZ/xcHwfNa9yqAAAAKTcDZvnVWYoWFhYWBUzkyphqPQWAzF3A4caN+sTtEjGDjBl" +
    "zRA55dstf2lpcg7BUFQaBo98GmwV8Sgqz+WBV3xKN/BoGgpVTEFNRTMuMTAwVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV" +
    "VVVVVVVVVf/7MMQ8g8lESvtEb05AAAA0gAAABFVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV" +
    "VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV" +
    "VVVVVVVVVVVVVVVVVQ==",
  "two-tone":
    "SUQzBAAAAAAAIlRTU0UAAAAOAAADTGF2ZjYxLjEuMTAwAAAAAAAAAAAAAAD/+0DAAAAAAAAAAAAAAAAAAAAAAABJbmZvAAAADwAA" +
    "AA4AAAlIACQkJCQkJCQ1NTU1NTU1RkZGRkZGRldXV1dXV1dnZ2dnZ2dneHh4eHh4eImJiYmJiYmampqampqamqurq6urq6u8vLy8" +
    "vLy8zc3Nzc3Nzd7e3t7e3t7v7+/v7+/v/////////wAAAABMYXZjNjEuMy4AAAAAAAAAAAAAAAAkBaAAAAAAAAAJSJqqe0kAAAAA" +
    "AP/7MMQAAAdcQz51lIAJFI+rtzTQAwDMAAEV0V0V0V1B2vxILAGYgcsZwtmiOXzkcollJGATDYrJ0aNGjRoECBAxAAAw8PDzwAA/" +
    "/Dw8//8QSiBJYBQOBwMAAAAAAA0pAVuUakpiQgLBCMugcSq0DDcmjEhi3sPGkCq+DZBXfBsnCW/FmJcPYKl/jhHKJaSQ9v/LyILC" +
    "AAAalgYA6P/7MsQDg8ggLRAd94Ag3wWhQb/slA2GBOgQAGAazAsAc8wu4OXMQKGPzXRlWszTYZtMGsBtTCFAWkwFIACBQAoYCOAc" +
    "KxsvMAAAAQkT+8UsAJgAwYyamaLBrMmcl/GB/hDJhAQ8oZu/2nGXXhTphW4IEYJIA1nLmxqQ6ZaFAYtFgpZjwPrTcUBQ4DkAoKlY" +
    "gUBWjMAfBlDBXhwE3Ef/+zLECwPG8C0IDf9koQAFoIG/7JD7tMHsJljELAl8wbkEgPqoziWA1I5MvHDFANOJnq7n5tbEWDFQMy4Y" +
    "NRMzhFY+GFMG0ApDEqwfI+96WAM++OozEeQzQwcoGVPx5DkIs1lWMyMTFRJIlnSdLTrO3//7f9H+xQaBTEQsMllcz0jDYLdOcWgw" +
    "i8KlMU6Htj4070Q1d8p+OFdcx27D//syxBMDx7ArBA5/hEDjBaFBz+yUCB/MDkYACcLhIgAa8HUc6Qv///q/7/6yQAGBQ2YcGxjs" +
    "umYksajg5gjQRAYSmPBmlQc0ZmSAJAYTcBhmCDgJBwxGaSHGTAYQRDwKvd04lS9VSNJAYQi4ELjCVUxSkMALBizAtxpA1NjmKMPp" +
    "H0TDnQfgwXwDtPJgjck00UqMkEwEPKtbEzmHsf/7MMQbgkbgLQoN/2Shpw5kqr2AABmkiJbdvlkGAcAsliMANmEuICYkI15u0qxm" +
    "X6FYYPAPxhDA5GCAAguEv+yZpjMzhI2ESQgty4fuOwuxY7j0zsMsg1L9Td8C2aANp9aMWK8Nv+1yHMY3L7j+Q5Ns4jFgTlAQeUh8" +
    "Rh+s/6GMACIVjsdj4aCAAAAAAWBCO+0v+XVYDr/8zoiUW//7MsQOgAtAhWO5nQAQ8I8pQzbwADNf5piIsyprv+ex8ZhYYtzQVrX/" +
    "4XHGnGDzUy4WrvW///LPhQIouXFTWlM7Kssf//9tIEd+GIalIp82Axb/i8QaUXu/4oqsp4qzH+DgR9zbgtMz8KxhBghGf+q1BKfh" +
    "PTJ//c4kOOvJ1lk//+r71l7Fkg178QhIl/WqAACgFwAADdWzpkSKRgf/+zLEBwJHpDczXdSAKLUFYQHf7QCCxgqEwcFwJDoyVMA4" +
    "x5sySKUxwC0MAVRJNaGh0hLE2xxaTA3+HQn/CYG/w6E/4XO42pasY54lUwoAMwTAYwXDYwDIEnNym4mjgm8w8aBgGpU6NBenrz/+" +
    "v////XXvMrMuWKdAxMYUgAYJAOYKBuYBeCVG1B8nJ+eBjDYVBKUulN352+7/q/////syxBWDxZQrCA7/SACvhWEB3+kA/1c7y1LV" +
    "1HQz7gIUTBMBDBUNjAKAS82EbnEPZxMScCgNVZ4ZixPXn/9f///+te87ZlzBTo1wgMKxgkApgkG5gEoJgavj0fnf5GGOhcEqq8Uf" +
    "t0V93/V////q53lqdYMdIMaChVMEwEMEQ2MAeBMzTgOqo6XMwZwQA1gnhiE5R3n/9f///+vvO//7MMQtA8WAKwgO/0gAsAVhAd/p" +
    "AHp5kp0qqgOFYwSAMwQDcwBsE0NDt7BTi9AAdEYJYFsUTn6K+7/q////1c7y/Os2OmEbCBVMEwCMDw2MAUBNTOMu0w2nUEnBQGsp" +
    "sMQnKO8//r////1q7zt6eZqdNm0GCsYIACYGBqYAeCbGWh9wpp+gUOjIJZLZInP0V93/V////q5nUp5Y0P/7MsREg8V8KwgO/0gA" +
    "rgVhAd/pAM6cJEHC6YNgAYKhoYAgCbmQDd1RmOoVOCgNYJ0ZVbuXRUgaAbPr////1wBKBsSKD2gkAVMBDAizAqQEMwcsADMGFBqz" +
    "AhwJgwNsEaMTWI9jH4q28wc8X3MWZDDzBGwM8wI0B0MDoAojAOAAgYmPqJKFicUkcVl0plNyvYt3rQLCoZMgIXDJkYL/+zLEXIPF" +
    "cCsIDv9IAL2FYQHf6QDMMubxb9P+r9//oQFGAYGu55gPABGHIIAYmg2hiZAeGixJgYwwHZgNcCGLwB0bAarBxSigGGIASYwo4hgE" +
    "gzmp8DgYKoAOcPAY0YBuoHNzdQG2HAbtWBnyvs2AcbAUIEVHH/4asDVgpQUuf//YmyLk+Tjv4IAn/4PmlQcACAWGrtcWkcJUypi9" +
    "//syxHMADRhFDFX8gAG6E2ODPUAAwAWcKnaYCq0wGgMpDKAtMEdENHpJyXE0UNQ1DVc+OigoMFBQUFApv/8UFBQUaJVMQU1FMy4x" +
    "MDBVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV" +
    "VVVVVVVVVf/7MMRLA8d0OzJdh4AIAoBAABAABFVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV" +
    "VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV" +
    "VVVVVVVVVVVVVVVVVf/7MsRwA8AAAaQAAAAgAAA0gAAABFVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV" +
    "VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV" +
    "VVVVVVVVVVVVVVVVVVVVVVVVVVU=",
  "rising":
    "SUQzBAAAAAAAIlRTU0UAAAAOAAADTGF2ZjYxLjEuMTAwAAAAAAAAAAAAAAD/+0DAAAAAAAAAAAAAAAAAAAAAAABJbmZvAAAADwAA" +
    "AA0AAAirACYmJiYmJiY5OTk5OTk5OUtLS0tLS0tLXV1dXV1dXW9vb29vb29vgYGBgYGBgYGTk5OTk5OTpaWlpaWlpaW3t7e3t7e3" +
    "t8nJycnJycnb29vb29vb2+7u7u7u7u7u/////////wAAAABMYXZjNjEuMy4AAAAAAAAAAAAAAAAkBJIAAAAAAAAIq0LL3ZMAAAAA" +
    "AP/7MMQAAAdYQwIVt4AJFgjiAz5QATT1M1dZNVRSZPMwbDnsQ9raPCjDNA03SSOUfjYkYy4cMOBC7CxF2MQFzHrJ2aZ1oeo1ezsj" +
    "x48eRABUwFcA4MKsHTjAdwIYwYY1cMBDAoTBkkngxn4G4C4D+ZjIC+GAXgfZnMwP+YCuDasxccwFkANacYIyAVqqB4W8BhEV/EUC" +
    "lR0A0wQgM//7MsQDA8f8Mxgd5IAJEQVggb/sWBkAYwGwujGLH0MlFWY/eaYzN4JVMLkJ8waQQTCXESMGYKowIQBjARAIY/OSuQGB" +
    "9hGoulUEjFli9NIYKGZkJsSsdjamCoAzxht4nKa25+Cmj3J0xgWwZOYCQCVGKvCwBiMQSSYHGGVH5jI4YQEoBodhp/aYkaCqv/+u" +
    "r///9aowsDEw1DwxKFf/+zLEBIPIkCsEDv9kgOkFoQHf7JQx5IgzgPc4DmwxsxQ1PPk+PTgTSecxBEgxMeNBpzDDgY89uSNuRTPS" +
    "Ax4LCBZcD4ODGjv/0f/+3////pMBQeJA9MABkMGSjMLkSMO4dMAYGfjIoy+Q/ltFLMvKBzzEiAKMwckB+O0MzWRQywDCCoeCVfun" +
    "AVL2IQuMKxpMZCsMqULNBGgNn7JM//syxAkDyAgtAA7/hEDzBWDBz+yQLgF7DIMUJU9XrtENK8NoztpfNnh4z4BQMfgwcjQWQJMn" +
    "feSVf2/7P8l/kv9n+gRgkwwLDHpVM0Ig1O2zh1wMHfCyTEJh3QzYuz+PkUk7DMsgWIwisBtOyGjTwEITAwjDAhBdh7sV9f///+sQ" +
    "gUwsJDHJLMxHw1CyzhViMHvC8TELig4xmcfqNP/7MMQOg8i0LQQOf4SA+oWhAb/wlJ55lTWkgPIxl8IhPoNo2qazOw8MjiUxYGjD" +
    "YVMCgcvA1+x///////965DAwcxYcMzOzXGg6/PMGOChjA9w98xOwAVMpwcTz66HzAzVwS2P46s1s0DLZ5MbEoxKLzDgeMFAYMBa9" +
    "J/uqbQHAZiAQZSOmpHB2riYSgJOGGTi7BhI4IIYWoIJGtf/7MsQPg8fsLQYN/6ShDIWgwd/s0Dkq52OB5ca++mYKtQYAHaSEgYCi" +
    "uYLBcYLAENBWVgBB7bKsGgHEgkIhmMiBzPHWrNj1BMIiBTzBHBIUx7YvxP5cWezE9xkwwuYHdME1A8DnIc0tAMIBy5RhQCXqdX/2" +
    "f//0/uqXRV+mWgkAGDD6dFfhvc1Glj+a2lpgeIm8ZmfHSGWMCfRh5wH/+zLEEgPGsC0QDn9IYNwFoYHP7QwEYIaAMn6AHBBmcFAA" +
    "MhPbhXpZVEWZDgJMAQg4imjGBzMRkQzuUjBPgVUxCdA+OZ1cbzKMROswAUE2AMGYcfGJj5hoCLCiMbZq3qbfQVFTiJkyRMMzJyZI" +
    "FU8wIgECMKHCCzRKJ487OU7bMaBAiTvA4NHh0x4HjBQaAoTEQGR3p//mS8Ss0DnR//syxB+DxuAvCA3/iGDdBmFBr/EMoAZoyBp5" +
    "RgFgF+YDGE4GBcmXJv2VG8ZhELsHWoaZ7IQsPR0EGCgaYVAxiAEM3tcq///TGSwADAWBQgxsMM8ByMaMGsAuTIh15o1/wTCMOWBp" +
    "DAZQI0wCAA0Nog6xTuqSWIn5ZbA38llV93/cUFA4xYATHIqMjnwyQyTHOcMC4EBTBs1II+r9d//7MMQsA8awMxAN/yppSolggc/x" +
    "SbM0aBsTEJwWUwaQEwNdN40+8zHFuNdJgxCC3wYe6FiH6SkpOU9P3C20ARzw/hDN89XVa1lVfFLws+lQDQZqGh5eJgWwJAYPmGgm" +
    "ZGP95sTh38YjgBgmC1gSJm9gkMGPNVAy0RyQCL5gKI1L2bA3F2v//+hbEm6gmARwO1CbgUBomBwgGRhYQv/7MsQrA8fYOwwNf4pI" +
    "2oaiQZ/xTaWZZcyYmPphn5giIAsYZPZrcwnHUgYkEZapYV2oyMGK///6z6q3ISTIU1sPGzAzA4MGoI0xCSJjGCg3P/FUAwCBIzB5" +
    "EPXE89QhzHogMFANAEul+rOQN///6pXKWKXBBoGAgVMCi4wwZzI8WMJxSU9Xv2zj3MhMQ4U0/ETgxRMhhgwoAwcAk6X/+zLENAPG" +
    "1DkQDHuKaNgHocHPcYTGorlLlf///7T8sSQTCIFFRQYLRGtADPMAVCpDDkwtY06UfeMq1BOoBnM8ROMWghMJwKAwOhgBK9hc3KsX" +
    "IchnDOGcLsYYlYo8XyIQ8sDQjMzBm4q25gIwR0YGuPomspLnZhKQraYS8DdmDLgHhgLwDue8QZJKGQi6qZ7+w1EY3Db/v+/8Pw5G" +
    "//syxEGDxvA9Bg3/rCGPCx8Bv+mJIxGKSksYCcAAAAA8PD3/4eHh4AI///8KFcaWzytDTWl3JzIJS2oANM4MyrTwHMICnMwDyO3c" +
    "cGaCOlz0Mgg9MRwUPB9OI0iWQlrUemJLGZ05TvQ9GqbHmVampqampqWlpaWziCu6CgoKFBQ3/+EFBQKqTEFNRTMuMTAwqqqqqqqq" +
    "qqqqqqqqqv/7MMQ3g8sEZvYM9yxIAAA0gAAABKqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq" +
    "qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq" +
    "qqqqqqqqqqqqqqqqqg==",
  "falling":
    "SUQzBAAAAAAAIlRTU0UAAAAOAAADTGF2ZjYxLjEuMTAwAAAAAAAAAAAAAAD/+0DAAAAAAAAAAAAAAAAAAAAAAABJbmZvAAAADwAA" +
    "AA0AAAirACYmJiYmJiY5OTk5OTk5OUtLS0tLS0tLXV1dXV1dXW9vb29vb29vgYGBgYGBgYGTk5OTk5OTpaWlpaWlpaW3t7e3t7e3" +
    "t8nJycnJycnb29vb29vb2+7u7u7u7u7u/////////wAAAABMYXZjNjEuMy4AAAAAAAAAAAAAAAAkBJIAAAAAAAAIq/1aNX4AAAAA" +
    "AP/7MMQAAAeYRwYVp4AJCIjiwzygAWto9gUCYMGCgbQgQKM0oNksOTNO3pPr5PvrOu5EkxmGBuGhpBgNcmYKcFWIePWXM01GoFYr" +
    "FYyPHlAMPD24AUF1CUYDQFIiAXCwgxh3gqmAuVWYrwhRroVUGOoL+cXKmRmCgomCsAMQCuGAICSaywSJhmgGgTBfeF0Qj38enBRw" +
    "cGGohKbGAv/7MsQEA8eENRwd5gAJKwXgQc/smKBsYAoLZhThCmBkD0YnpAJsA+hmMgAMYfgZ5gpAemCgBCYAoAywQsAED4QtrF7D" +
    "eRQkYssBAGFQcFhCFyABECYNjhUDPTF9BX8xtgcONix7xz2FZj4zGsH3MRCAlTCFwIQwT4BXPLJhb9M/FzAyElElDaC+AgkninIf" +
    "7f///9tIIMHDJQU0ASP/+zLEBIPIsC0CDf+kgQ0FoIHP8JBrGztAQwT8CQMHUDgzFskzE/jqw3M63EATG1AeM6lSQ1uLkzhHIyOE" +
    "ExVBAOEAUAgKAGqaW/////////6yYDmHgMY9EJmQgGoTScOVBg+4KCYlkJsGS+zcJ/LahwZXWFpGEkAh5wNGGjiiZTFxi4KgYVJY" +
    "NUYbD1nZ////kf//pQMCgYSMWATK//syxAQDxmArCA3/pGDqBWDBv+iQQ40wzOTkjBUAgExccDHMCH8hTNzwSw47AszQBYxBAMHB" +
    "AgPVw19yIxT4aUuhoQAxuZwKG5op/XMYWqMEmEAoxJ/j7DgYwgQ9mMLg35grQCgJ3gFlBTIOGpnNpEJTW/////////6VMAgRCoTC" +
    "gkkpFCJKzFHbDFGhWkzZ7xeNVjEYjBBRKsyGAP/7MMQRA8aoLQYO/ySg/oWgwd/okOmMGGAQCD823jQNAQyPsDTMas9MJQwMJBHM" +
    "NRuMZi3M/VSPhC0M9HP8z5klM8xUYMgMHWCVjEqxZYwvoFQPUGMyLAABE9YRnb/xS3z//+j////QMljAzgHQVbjoRSMK3CqTHkHM" +
    "49lThfNUuGwzd9YjHQozh3QDz9yTG8ZzDUEAUFIkAyrXXv/7MsQaA8fAKwQOf6JAzQVhAd/wTCc1j///X/p//+swWAwxZF0yqNY0" +
    "9h8wmQlsNb89qjW1SwIxn8DDP6Pg1ZFDIdzN4Goy6NhGDU9m4x6vbvdqMXo4wzETAeghwwNEWpHjDc+ZNkhMVEGYDDFQiU8RWjcT" +
    "oNrsM28mDm4EAw3Yg/8Yp8wz6/9Rq6QmafsYDAIPmE8mUBzBUqkeKen/+zLEJQPGtCcGDn+AgOWEYIHP8BAgGC6iRZgmwQcb5mZs" +
    "dJm0iIarCZqJLtMhc5bCH1/////////uNUQs0L7jA2hP0yEU0NPhjMHDICxT4yd9TEj8MpokyqKQxeDx6MNAG/0wY8K8MDuF5zCj" +
    "VOo+7iIUPNRQ1DD3hY8xxqow5YM4reOOSgWZi1yHHwj7P9vp//+ns//oMCJB5jBD//syxDGDxSAfCg5/gGDQA2AB/uyARiUw/0gE" +
    "PrdIeDHXxTQwBIIHMbRYyCpTlZDdIgNvHlijKTBJQakxZ5AeOdq9DjerSyg0txEzYUw5/JNwhDU1czktMoDBIPX5unPA8DN1MQbC" +
    "dDTnujIwIFjZMNQFkDvdezW4tj33c5xONhTzKzUxYSLvv5TAUFSrmf/1f///6jGcDlc7tf4KOv/7MMRHA8UAGwgP80QgrYPgwf7s" +
    "RdGcg18wmTJmAjMUsCA8gDB32aANGEDwyHrKme////9aMFBRbz5sFLM5dCLTI9ESP2lTg1Q0grMjCh4BX0mK16z3GAld0JsShCGa" +
    "RykFD9HCEGRLEVQVVAgiGio3sv0+nNxUMfDDLToYdgyUwhSQwxiPUTDAyhexfckb///////6wCk24DesSP/7MsRgg8YgHQIP92IA" +
    "ooNgAf9sCFMYMeU5uXjKxhOeaMsbAypAKx+Mw1Lbedenp7dgEAQBAMdRn/QCAIO6gQBP5cHwfBwEPggGAz/o/0I3s+DDxvYIMSYi" +
    "EwJAeDCQC9BwHByrpoApnF5myRhRRkRRhQhgwBbZB5MZYzkw7ymhp/nKcpynZclyXdBEMikUoZbcUKFChIUSJEiRIpT/+zLEd4PE" +
    "JBsCD/tgIHIDX8H+5Ayl/KUpLIkQKCgor8QUFBQoKO/+BQUFApv//goKC0xBTUUzLjEwMFVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV" +
    "VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV" +
    "//syxJyDBEgY+A/3IEEBhOBN7mgCVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV" +
    "VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV" +
    "VVVVVVVVVf/7MMSvA81cfuYPaSXIAAA0gAAABFVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV" +
    "VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV" +
    "VVVVVVVVVVVVVVVVVQ==",
  "bell":
    "SUQzBAAAAAAAIlRTU0UAAAAOAAADTGF2ZjYxLjEuMTAwAAAAAAAAAAAAAAD/+0DAAAAAAAAAAAAAAAAAAAAAAABJbmZvAAAADwAA" +
    "ABEAAAseAB4eHh4eLCwsLCwsOjo6Ojo6SEhISEhIVlZWVlZWZGRkZGRkc3Nzc3NzgYGBgYGBj4+Pj4+dnZ2dnZ2rq6urq6u5ubm5" +
    "ubnHx8fHx8fV1dXV1dXj4+Pj4+Px8fHx8fH//////wAAAABMYXZjNjEuMy4AAAAAAAAAAAAAAAAkBVgAAAAAAAALHotyRAAAAAAA" +
    "AP/7MMQAAAdwRyQ1p4AJEApw/x+EgiAl9PDac4FBmHFmLCpjGSPHDhnBbmpMg4m6SEhBxkkBg2ADQA4AwD8XIk4h5L3CAwMjx48o" +
    "Bh4eHvAABloAMzczaHuID8AAAAAAABShJMjleCFsAYBzhJ3EuwvHUR+u1UrMhYDfjRSR7rhJ16SFl0Mxkv5/zMo1lO1aWzmBaCq1" +
    "+Iu6/qHIwP/7MsQDg8hYPSgd7oAhCIciQe35TSwEDApBOBwORg4gCGCENQbJQgJiCBGmCkCKYGQCLHAoACAAFwgCEGBeY6E+b2TE" +
    "Y9jgYigkvZmLNe7rdcVoSjBMAOVgKCQNxhHAQlCTRmyjOGQHiccm9h5i7jbHBXJoLAZEam7xQJB1IAgA0lCcNgOc8wAALh0AFhEF" +
    "xCntqnRYQg2FgoAkZhj/+zLEBQPIfD0SDf/GYQ+HogHt+UywZj5nsNBgHIGYYY2DFmy5hzRhiIBOPDuhwbwkDaYHAJYkCINALlzg" +
    "aEOaMkyBgLgTl9GZwBK6Sxf4/TVk4xoAgSAvDgdCgScyWgADNaGFMZrE81KLPjEEG3NftjLmExE2NZCjDwBBKOgEmAYEUZmNP5gY" +
    "AUFu2APvDErp7HZ9mjpkCoChYGgC//syxAUDyGA5Eg7/yCkTByHB7flNJJgkZxjmK5lMaZ2UfprNAOOYVwADmGqAUAgxQ4GowcAD" +
    "WDLkGABjAHBpMRSL4wMQG0JDW4YldJgOgVoaXAcAWCgLDA7AHMJQB4yYQFTNFFoMSXCgxCrSzB/GyM4szHVowwtNzEgKIoqIMmAY" +
    "DsYqFVpgoARAoANdjlxiN04mfVsS2xwABUExAP/7MMQFA8hoNxIO/8gpFIehQa74hHAJK8wUEQzhNA57k4038AbMJhAOjC4AbMFU" +
    "AgwKAATAkASEgHER4IMA0EEyOXmjA9ANQ0a/DkvpAOFL0QHgooZ8Ocg4ZXiqdcBYZzQvZhcbEm3nmIYEo85gGhkGAQDSCQQDBvBt" +
    "LXLbLJmBgDQanl5Jg/AOA4BtSxx4cjdPY7V9m6qNIdyAEP/7MsQEA8gUNxAO/8gpGYcgwa74hSUNx0qDCIQTSg6Tn7czTGAa4wlo" +
    "BnMLkCowVAEQMCsYKwFxeJqCXhgJgXmhm5cYJoAaBjbxSX0gHCFLwcAMiFNMUOu3MyCQPERLM+sYIwAO3Dyy5FMPYhgwEw2yqDgK" +
    "AbmDyDuAQJQYAQ95gaAkHIZi2YVACQYBejQyd+IfpwOGXiaKn8SASMj/+zLEBIPIGDcQDv/IKRGHIMGu+IVQBCJMWQwNNzYOKfeN" +
    "A1CczCAwHYwnAMTBHAUMCAAkwCAUhoARibLTATADNPlZoMCTSYb+QT9gDi66C45ighny5xnBlSTp00JhmZCQmGPjKfVODhitjemC" +
    "EFgYBILYUA4MFcMtiCSZEAuYHwAxz4SshAnBEBWng38CS+nIqpVEXiZ6jsIgFTAD//syxAWDxzQ3Eg9rymjoBuIBjniFBaMGQBsx" +
    "DAqzGaOHO+Yn4xdgaz3pjXDQUmNA6QebVsxQAcaRZxhQDOoxB9FbwI2IfZwoOWkN7zHREOLhkxSQXDCMVAOAxT8wwgrjAjA7AACR" +
    "ecwAwR0d18MqAwBpqSGmkQOKrnto72dVlMqiLck9RCAUYBAIpg4gHGIGEwYrJwRzolUmJuDUdv/7MMQPg8cgNRIPa8po5IaiAY34" +
    "hROaMYYoCSyG8ibDTAFACNGUjwaBSYrCp2+QzjDlrCF3zQ4y1DPiFjD+A1MKlDk4HUUDDPCHMCgCgwBQCy3ABBTag1NaxgDAFmmo" +
    "OyJAqrOgWevNqqaUw04KtwUAHMA8DwwigCzEYCdMUg985EjEjEgB5OmqNAPAxIwTxFJlrXQCAcaS4kQYCf/7MsQZg8cMNxAPa8pg" +
    "6IbhgY34hEvWLTt/lSG2sJfggBruZgsH5kJh+gRGHoiodIyR5iKBFGCCBSYCABBa8GAqqzsYTSMAICU1nAiQUC6rE/Mus9qljUZd" +
    "pYUEgBGAoBiYUIAhiUhPGJmhYcGpt5iEhBHKXmdIGIBmDnTspUxAIDxpGg7g4DpgsPUoy7DDK05AaM0aMrYT3CIDDQn/+zLEJAPG" +
    "8DMOD2vKaOkGYUGN+IWI6eKdkaEBiag7mCYA8YC4AYKAEIAX0YFxphGAEBeatwtxgRAAq6h2XC6XRmHnFU2MAAAEwIwLjDOADMWQ" +
    "LkxRFCzhARCMRAKU6L4zxkxIQZhF2l0q2g0C406x+TAZAAYjD1Kdq5E2kJzhQRl6ZIzHhkphPgBmJ8ZId6R0ZioAvGCuAmCgPBIB" +
    "//syxC8Dx1AzCg9rymjoBmEBjfiFMwGATVO2MIzBQDk1ACtDAUAFXdDNMSqWy6KuspaCgCjAoAhBQ4Ri3haGJKp8bgKRJh2hWHEg" +
    "mbNGGEmbnPvFUqQaBsaMJgZgEgCMphqqVuxB01oF5wILGKrJxg8YKgDhiXkRnWmVgYm4HJigAAcG40BAADtFhj67hEGJ+JmQAANw" +
    "ojWq3ZdFYf/7MMQ4g8b4MwgPa8po14ZhAb90zU0FM4MAVMDcBYOIlMawM0xJmJTZoVqMOIM84s4zSMwowx7At8u1Q0lBANCVFMKg" +
    "FMxj0zczWmoDZAkeFiDBnMNH402MTFZPPWeo+fC0zGuAyBweY8DARAVmBwBzAbPEOxYBLM9pPwgANaNBtBdwVZbInyammwPANGB0" +
    "AGUEdGNaGEYe7GxpRv/7MsRFA8cYNwQPa8po5AbgQZ54jbKmFiGgbSeZNEYIaa9wre8iaJVBAMwFPEQAEM/jk3UzWmYIZmloISQR" +
    "MYPQJnAYGFTUfBbJ9bkFGN2AWTB+jQNQ8BSYCgD48AgqNgQqCCZPywBgAgFsggOYr4CVeZZiB4YAoCgQwME4PC9mX8AQaJA+ZkJf" +
    "Nm0ZyAYqhGJwfYaE+mOpRvYwYuD/+zLEUAPHGDcCD2vKaOsG4AGeeI3CABCoCZgPBcGgjqiYIwHwBAJSoaW+kN09jpE2ZRxAeGNG" +
    "0IaMpV2MxEwzEcw9Wc5YXcw7DY0oGMnKRQkMWEQ5DMaHBAZGJIJt+wbWNmAAy0WpOJE5TR2M7fsiMLCy05GQvIGTgc4HIWmLTkZC" +
    "MhachOzI1I1OztmRrbW2dN6a2ztnSgoVFAOE//syxFoDyMQ88g9vymGhB+KBnuzJFAkggcMHWm/AZmoUxMSAzTwOQpUDumUAIOKq" +
    "HCBwxoKRS0W6OXAkiAwb+geSHpc0Z+hXGUxBTUUzLjEwMFVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV" +
    "VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVf/7MMRGg8ccNwoMZwSAAAA0gAAABFVVVVVVVVVVVVVVVVVVVVVVVVVV" +
    "VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV" +
    "VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVQ==",
  "marimba":
    "SUQzBAAAAAAAIlRTU0UAAAAOAAADTGF2ZjYxLjEuMTAwAAAAAAAAAAAAAAD/+0DAAAAAAAAAAAAAAAAAAAAAAABJbmZvAAAADwAA" +
    "AA0AAAirACYmJiYmJiY5OTk5OTk5OUtLS0tLS0tLXV1dXV1dXW9vb29vb29vgYGBgYGBgYGTk5OTk5OTpaWlpaWlpaW3t7e3t7e3" +
    "t8nJycnJycnb29vb29vb2+7u7u7u7u7u/////////wAAAABMYXZjNjEuMy4AAAAAAAAAAAAAAAAkBJIAAAAAAAAIq8DrjUoAAAAA" +
    "AP/7MMQAAAdYVSAVh4AJE4vstzLwA4ZBpzns/9Op1MjRI8WOBAUtB9TeTuAsImIqRlh1oeh6HqNnkL4PQCnANwAsAfjHMAC4BAGI" +
    "+mhv39w9uAD//1I/X8AAAAAAAC2Sl+2GuqonW7hMC8JdpygeSn2bpjWi/cYLYSBhcPjBRi/5QhWeAM0EbhLbkITi2xaP+4TErBUy" +
    "AYAE00pg2f/7MsQDgsh4TS697YABBYmkAZ90gQgARMCYCswPgjzEoQZMIkIcwSwAQEEGYAwAJgAAApq0T7RbfcefqSQ01qegoChR" +
    "iZQT05vhGGAL5Q9TWcXKayuZE0AkGpiYLofRneQgHLI6GBJEmWRXmHYMAYDUwmuw9Le7y/9wDAkXirdRwAgCJppBapiGG4MABc7s" +
    "Q3L7C1WTMnR8BRZrDH7/+zLEBIPITE0cDPukCQYJ40GvdIDCYVwOhtomOHmheGPx7GEqPAUJxwAmFvRH5ivnzv7gt3nJZ0l8DAHM" +
    "ERWNDscMvQ0MCgBUGf21jaFvCvhBGFBhgUplMBgki5mdtYyZvpOY0jWZYjaJFQTBGog1eDpHSYb/7ij0FvhALTU2Q4SDhMUAE+g0" +
    "GaTDN34lFfRhywqQxZ0w5I0kcwhR//syxAaDyLxRFg17pAETiaKBr3SBTjT0rIPHSgMFy/M8jvMVwoMEgHLjLFcaM2t5c/NurqPO" +
    "8q+RgDDAcbTXrxTFsUQABSVbKHbjc5b5By1y+ACJmeGHJUmGYEYb651B9gbhkskBhWphgGGIwAyqbYILmKfPnfxetxmcruQlAQDT" +
    "BcZDUbjDOEQDBABUinJpsbQueFfCCMKDDApTKf/7MMQFA8hITxQNe6QBEwoiQZ90gIjBJF3M7azMzbSkxrGsyzG0SKwmCNRBq8HS" +
    "Okw3/3FHoLfCAWmoxhAkHC43GfQADQbpMM3dyUV8GdMNUCLqmGYbnZg5iRGjJL8dgkQYIlKZpGiYkhAYGAGgsxF3pblvLn5vDAkD" +
    "wKzEcAgwBF81C1kxHEUEAMpW4D/y+cv8kzJ0NAUWaxB/xv/7MsQFA8hMTRAM+6QJFQnhga90gGFkD0bdpph58YBkEfRhGkQBCcYA" +
    "Jhb0R+Yr587+3rd5yWdJDAgBzBMVDSbGDMcNDAwAVBndtY2hbcVFBGDBhIwq8zXQwVxszQ+zlM+1ZMfR/M0x/DjMJgzQJKffKRyy" +
    "pvX3FZnrbBALJSYAwELhzWURpEBAkI48AC93EjFPhX+dlrSmJao1fMH/+zLEBQPHmE8SDHukAPYI4cGfdIEULwy+mbDdkUjAMaTI" +
    "YhzCkDC1q6ndjVL3+//x2KSOWvCk4FQ3MzJDMIwnQwaXDEbp7HaJ11cF2zMAOlUwhAWjVbKWOfiQMXi8MEzaBoMo6NjgibqZ58/9" +
    "wXDz+uUsMXNMCQ6M5paMlwgBwCsSh0JCVYi8CwZfQKomJ0YE4fJk9PYmh2GY/H5n//syxAuDx3BLDgz7hAjuCeHBj3SAMfjRkKAO" +
    "p6D5NbsYb/9Nij8kmYFYuGBw7OZgVRB4Jr8geWUhaNP65S5S6xmyYHYURlSLTG0IiGAIsmOQ6mEIEF8WJP7LrPf7//Mzk/OwCnYI" +
    "QvMrIBMFwfSodOGJXbsdon7ZYnWDiHlJgwAgGhGQMfoNRkJGGB1IFwash65JQ1M+8/9x+XRl/v/7MMQUA8ccRwwMe4QI7glhAZ9w" +
    "gWtJUmARMaw5BnEJF8XGlpUZEXgWDL6BVExOjAnD7Mnp8M0KxTH4/M6j8aMhQB1PQfJrdjDf/psUfjkzFWLg4QHazwBqIPBNfkDx" +
    "ikLKjT+uUuUusZsmB2FEZVy1htKIhgCLZjoO5hCBBdliT+y6z3+//zM5Py2AU7BCF5lRBJgqD6aDpxCV2//7MsQdA8dwTwgMe6QA" +
    "44jgwY9wgbHaJ+2WJhgoh7WYMAIRoVkLH7DYZERhgdSBcGrIeuOUNTPvP/cfjUZf5rSVJgETGuOMZzCRfFxpaVGVjrwLzRAC5pgY" +
    "GA+G2ZFDbpm9VmNRmZlGY8VEY2rQfRW8MN/+nqm5iZirQwgKHPTsCooPAtmkDyykLRp/XKWFLrGbJgehSGVstobViIb/+zLEJoPH" +
    "PEsEDPuECO6J4EGPdIAAi6Y6DuYQgQXZYk/sus9/v/8zOT8tgFPwQhiZSQiYIhCmg6cQldux1aJ+2WI/goh7WYMQIhoZkSH8DcZE" +
    "RxgVTBUGrIeuOUNTPvP/cfjUZf5rSVJgMSGvuIZ3CBdFxpa2MImIiohILYFpDAQKMHAY0BDwIC6CgcGuO7bvv+/8bjFJSWMNfhhX" +
    "//syxC+DRxhHAAx7hAmaECMFzKT7htwznEBzDXHIhyMS9vfCCBAgDYrFYrFZOjRtw9znOc5sAAAI/gAAAAGHn/8cPDw8MM/9gAAA" +
    "ACv/4AHh4e///NUAAIqv7LZhTILgGzkfLgWfDlmNFoljMSf5XRre0J9Gt/WzEZ4ANCUsT5XK5WgEAgEAgEJIkarzJpEiRJEiRJKq" +
    "rf6qqokSkP/7MMQjg8ykkxRMvM0YAAA0gAAABFBTfxBQUFBgp/9CgoKCgl38CgUFBQU3/BQUKCgp+KpMQU1FMy4xMDCqqqqqqqqq" +
    "qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq" +
    "qqqqqqqqqqqqqqqqqg==",
  "glass":
    "SUQzBAAAAAAAIlRTU0UAAAAOAAADTGF2ZjYxLjEuMTAwAAAAAAAAAAAAAAD/+0DAAAAAAAAAAAAAAAAAAAAAAABJbmZvAAAADwAA" +
    "AA8AAAnlACIiIiIiIjIyMjIyMjJBQUFBQUFRUVFRUVFRYWFhYWFhYXFxcXFxcYGBgYGBgYGRkZGRkZGRoKCgoKCgsLCwsLCwsMDA" +
    "wMDAwMDQ0NDQ0NDg4ODg4ODg8PDw8PDw8P///////wAAAABMYXZjNjEuMy4AAAAAAAAAAAAAAAAkBpEAAAAAAAAJ5W9Zwb4AAAAA" +
    "AP/7MMQAAAeMSShVjAAJD4nr9zOQAwMADPOnp6eNv+w9d6EgCAMAEcEdzXc+/PKU9jrs8xBy36UwSIU0gSJrsXY1yHIxSUljAPDw" +
    "8PSQP/8w8fqPukGl5fxuAAAAAAABGH8xx/2KgILFHrzhIBNIY0IuQP46JRK3YzQ2xmEjExRwfob1vQxv9Fmv7MzExUhrE3/L3bBZ" +
    "Vf///bsv6//7MsQDA8hAQRwd7oAA/ogiwc/5gIqlJc0wIgPwcCoYEYKhi2phGqlAmZJgupiXB7mSZLGO44GZITGVZyGhvDH6B4ma" +
    "RAiQohUBkkVlFxmtWv//+5BbVGkpqkwPDBoY9ApooTHs1+aNKJNGEpgMJgTgCYYFgKBgKg6mC0AIAgDDBBQkNSoAMiAWahF6e5dY" +
    "1Rr8YaXKisYRGZpx4YH/+zLEBgPHuEEUAGPCwSkIIMG/+UhAIZgxhZGKMhafiD8xjvBhmCuAkFgHzA1BSMMQA0wOAEzBJP0NaIBM" +
    "SAaaDI69aqxqj///7bNCYCBQqYMRjqYYLFmAVAfxgN4R+YK8XFGRLNTpgvQV4YGeCOmFiDqYggIxlqgcGEyBaYScEx61AtmBqAEg" +
    "bCqGGoZJQDoP///5hu6wDVVCQME5//syxAYDyExBDA7/zAEQCCGBn/lIhgDBjGIJmcUxzbm5sE5TAYaGB/mB4ATRgvBCGCiFeYfQ" +
    "BAKBoMGNFY4igMQ4DJVsDyuaqovUf///VdJNEuEZIxqHnS4YCcAhmBUgWhhAQi6ayEOZGFuAWIcClmACCaYFYRhhaAKmB4BeYK5r" +
    "RwBAcgoCZasiqyqlSev1+48hvwBwEDCEwCVgDv/7MMQGg8hMQQgKf8pBGoggga/5SKo6BRDgL+AR/AxmlGTMB5ByDAOQJ8wXQHTC" +
    "iABMdkCgwYwETBHMkObQEsDATLppsaalJQAr////MMjR4Z2kIZUybqEYDuBEmB7AnxhbIxWbZah4GHfg2ZglgHMYRwVRhLhomNkA" +
    "ERBmmDuVAd3gMZgQgAJcvfNyqMkIBF////uvUsCj0AgGAf/7MsQFg8hQQQoO/8wA/YggwA14WAQmEoBGJQLmUIqG91ImpsBYRhWw" +
    "ByYFOASmA2CiCQhDA6AJMBoC0wNQ0DdOA9AwBzOabGXUqd3fyh1TYtCYQeYVEYaGYCYQRgcCemGq2EeHvJZixi3GAIDWNA3GD8B2" +
    "YvoFBgpgDmBGDCcXQJ4CAKazNXp6yh26+o/7LGzptAlE0sDA1BpMH4P/+zLECIPHiD8GAGfC4Q0IIEH9+cDwxjVIz510MMf8Uswp" +
    "gmDBYBcMG8GciKYBQSpgaitnAECSCgCmWz1WmpUnv//+hbInagKAwAkGAHI8A7FAGyDgcYwqQE5NtoDfzDogDwwPcBnNHfzELwz0" +
    "JMASTArKJOXwGcwBQCFoySikU6QgBcr8pS5SpS4IJMYrmAiBwYGwTphknTHRa6uY//syxAyDx0BBCgBjwsDuCCCADPhYmoWBgSAO" +
    "mAKAMYGQGJhcgHBgIYNHNNRAClTKO1OX8Wjc/CXt4yZEIZTAFxgLgxmCMHoYeajJwe4gGJWJqYNwPxgjAeGDOBuJE6mCIAKYC5hJ" +
    "toAil3nZrY2rKqXK+7HGxukvYeAgQKzGgIM8jE8BBD+kS5Mg4GIwiwRzArBDMBgGASDLCoEIXP/7MMQVg8cIQQYAc8MA4QggwAx4" +
    "WLRNVoDdI56ZRYv3mFc/UpcJUpckAiNDzAdAqMEwH8xCzIDxdXLMYcIYBBEioDRgQAimEaAcJAZkBd5pkAWr6j9JYv3mjcr6kbeq" +
    "XBcIcVGMgKDSYCwgBg4q1mRfjcYNYnZgiA6GB8BIYNIBoKKBMEYA8Ao3mysCSiE8Mxeo7y2r33Yg6cEN+f/7MsQgg8dMQQAA58SA" +
    "6oggQA74YHQMEQHMLgiMcRnNZoqPkBrsx5AmjCHBVMDMEMwLAWCsJ8wDwHwoe2acwHKdjxwxST95n179R1pSwpeEDCNwzAnAYMF4" +
    "FcxOSaj3TPLMb8FAHBcAwCgwCgUTBXAMHgHwIeiaJgFq+InKLFu82K99SJpqPwJECi4hwEAM4FD+MC5Xc15L/jCGEvP/+zLEKgPH" +
    "JEECAGPCwOiIH4Ac+JAAwGAwMABgMGMYnAAZghALiBYU1lgS0PHjiFijvMKoqv3KIblj7l/DAcDTBwKjFEezQ6pjqcc3MWgKgwaQ" +
    "TzArAxMDADwWFaMBkBMwCEFTOyAtUoduMUlu89V79R1uzDUUQwDBghARWM0CU6rfj6NEXMd0AgwbgGDAKAyGAWTANAKKwATAMR5M" +
    "//syxDQDx1hBAAB3wwDiiB/ADnhg54CtTB/5RSW8HqvV/GXOSsYuEDEgnhgCAhmBCFgYRyAZwfQ2GHYGeYA4GAsBCYHoDBhqAAmB" +
    "MAeYAibJnAAXpyPvKKS3Yeqi/dJF5C2FEAEgaYGBYYYj+ZcWYbiDi5h4BTGCSCGYEYEJgYAQBgqxgNgDmAkgCZRgD6gj/xikt4R6" +
    "8nIiAAH/jf/7MMQ+A8eAQPwAY8LA5ogfwA74YNvVJGH8chri71TqBpFoZmUB8Z0tB7IhRSFyyqfg5IR8cgmH6/8OBIBoDQDgEwAw" +
    "AwJgfEcnn/tnZmJYliGDcG4liIsWOU6b3WLFixYscoBn+AAAeHh5//HDw8AAP/AAAAAQ//8DDw8fLYyAAsFgSBIEgSDQqRZQidpG" +
    "5EYGLNg0wWtNetWlov/7MsRGgw28jyJsbYyJupPkzJwxaIOuK/r+w0/0ajSpl3Ned6NY4dEoQgbASAkAMCIEQaiKTT13FxyYmJiY" +
    "mJiYmK5cutO1ZWrly5cuXLgawaBoGQVBU7lQVBUJP5YGgaf6hKGqTEFNRTMuMTAwqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq" +
    "qqqqqqqqqqqqqqqqqqqqqqqqqqr/+zLEHAPAAAGkAAAAIAAANIAAAASqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq" +
    "qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq" +
    "qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq",
  "pop":
    "SUQzBAAAAAAAIlRTU0UAAAAOAAADTGF2ZjYxLjEuMTAwAAAAAAAAAAAAAAD/+0DAAAAAAAAAAAAAAAAAAAAAAABJbmZvAAAADwAA" +
    "AAkAAAY4ADY2NjY2NjY2NjY2T09PT09PT09PT09oaGhoaGhoaGhoaIKCgoKCgoKCgoKCm5ubm5ubm5ubm5u0tLS0tLS0tLS0tM3N" +
    "zc3Nzc3Nzc3N5ubm5ubm5ubm5ub//////////////wAAAABMYXZjNjEuMy4AAAAAAAAAAAAAAAAkA8wAAAAAAAAGOEdFOWMAAAAA" +
    "AP/7MMQAAAdcORIVx4AJEYnmczqAADR6JM/m0yeIwIRjQi8N0QY4hBjcSgMdBc0UrDVyYM8FoyALjDwSMEAIuImIsQQ8eshZczrU" +
    "avfx6AAAAAAoiQiExQAAAAABAKMMH0MIAjNGZFAAlmDHxnAw8GCYNnGAer5MGhtqs5gsOCVFErAK8wjlHeFhEHNt/UIgsoK4P4lV" +
    "MCRBZDBnwP/7MsQDg8hMKwId8wAg1gQfwc/0QOIwLAIZMTaJlTOckWM+4yqKNArMCjGzwbwwVIFxMDzAyjArAc0weIE9ME+AZzAN" +
    "ACsDAFLTZJDwKrbtRgkXCEwmJFwZxzZgswzwfUTY9m+VmGWKGmOxHGKwgGMYOmLgIGqI3EQFyC2A9P/////////YMBC8wEYjHLBN" +
    "JagwcEapPpW0KDr27zP/+zLEC4PG5CD6Dn+iAN8EXsHP9ECJHjI8nzGMTzGoKjGMIzYodR4CIXYBzR3f/1//////9oJFhhEymTGM" +
    "a52phDg2UfLD4Wnx2HGjKXmUxWGNguGOIcmNAZG4o8DwHwJbwC+/T//s//+z///VGBCYYKxlVXmwMIYRaMCnhceFR+7YZpIiRlKU" +
    "ZjKLZjIHhi2HJuANY0AkXsA5o7v///syxBgDxsAg9A5/ogDYBB5Bz/BI///////tHAoYfI5lhLGxaqYRkKiHQ+9v5iCQTwYJSB7m" +
    "oEsZcLBlkemTh4e5LiEcUtgnp7/////////sC4LMRDgy2gTY0mMIzEjTgpukoxDMIxMEqA3DTaJMqlUycPjIY/PVE9GiX2Ac0dwE" +
    "ADJSs1pqPF+zCLA9w2SvihMRAB7DBKQME0ofDP/7MMQmA8XcIPAOf4JgtYPdwb/wTJhQMhj0xwQDzpAT7lgOH/pVBwWZcTG1sp8H" +
    "kYTeHWmo9fGRiboPSYKcBiGpUKZRLZkQkGNyafEH6akvBM59AsIGYjJsyce3imEuBfBmLvceYmcDQGCigVJpo7GRioY5IpiomHrR" +
    "gruWA4f+lSYaMuDDZTs9KaMJHCTTDdOKYxLcFdME4AjjSP/7MsQ7A8WsHuoN/4JgtIPdAb/wTJpMfk8xYQDEJJPKCViFOCZz6A4p" +
    "M5AzcC4+mFMJ8B5jIRPQExToFGMFZAiTThsMgFYxWSzDhUPah5idIDh/6TAUwHAwQgDIAgEAYGQGVmRWlLZpyvJEYcsRnGP6CRBg" +
    "2wDIYBwCDGDyBDxgrQBoYMsAEmAKABDu242PP+gwiYM3MmXcrTAig7P/+zLEUYPFoB7mDf+CYLQD3EG/8EwxE6XDMGNA4zKnjq81" +
    "CYJRBACeYnSKgpcmnhhtZgBwCIYC0ALOqJAnqzDANgCWAvBVhyPyANhL/5cLhiPP/x5kgaFhv/+gYHSXKZh//mh50DQ6b///m5gz" +
    "OgaLN////N0NYAAAAAIEAAAGADABIyKaSFCod/h3OAhAxcWhn/UEdSxTf4B470Rt//syxGiAB6Ai4BXwACG3pZzDPtAB8+smHkqH" +
    "d+TwHgDwfB3Nr/x1m76Tk1NUjb/3mhocPvNp4lv/973nGMNXOd7v/8/fL3sZUtbDncO///f73v/9pqauCkxBTUUzLjEwMKqqqqqq" +
    "qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqv/7MMRXAA0hGx05tYAIAAA0g4AA" +
    "BKqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq" +
    "qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqg==",
  "chord":
    "SUQzBAAAAAAAIlRTU0UAAAAOAAADTGF2ZjYxLjEuMTAwAAAAAAAAAAAAAAD/+0DAAAAAAAAAAAAAAAAAAAAAAABJbmZvAAAADwAA" +
    "ABEAAAseAB4eHh4eLCwsLCwsOjo6Ojo6SEhISEhIVlZWVlZWZGRkZGRkc3Nzc3NzgYGBgYGBj4+Pj4+dnZ2dnZ2rq6urq6u5ubm5" +
    "ubnHx8fHx8fV1dXV1dXj4+Pj4+Px8fHx8fH//////wAAAABMYXZjNjEuMy4AAAAAAAAAAAAAAAAkBVgAAAAAAAALHrPmJv0AAAAA" +
    "AP/7MMQAAAeERRYVp4AJCoclAzxgAS95jTpq2pu3ZsUYkbAhI0jQ4kI8dk6L804tDkYwkZIYAhiYCxBDxcydlzNND0PV6vVisZHj" +
    "x48AA8PDx5gEAXmAaA2IQBgIO+YDIFBg5DCmNKG6ZJIWpqEiemT6MYaWSNokYQYGYBSfJgXAFswMHACMSAKS0JATcrJNm/EKGlUS" +
    "AAzAQAEEwP/7MsQEA8hkKQQd94Ao9IVgQb/oWCoB9MDGAKTBFwX4wdsXgNSZX2zkcD+U47KFRM4aFqzCFQ9AwsADUMB/AQioAMGA" +
    "ngFSgKm4OABQvleEmUmxkiiZTBGdc5gMoPEYGoL8mGT+tpmPwP2aRXz3GTFgjZiN4RQUBnJ7ihILAoBB1dUVrS207//9f///+tUw" +
    "AFjH5TM/Jg23BTBhAeT/+zLEB4PIsCsADn+CwRKFn8Hf8JAw00UDNFgubzeySxc0lPu9MPEIqDCGBgkwLEEzOfBE06IDLATMZgIS" +
    "GIsB1g2ZQye///////6zFIPzHcODKwQzQ8cjdJBT/PlDT+oao6SEX2OzSo2DJkidsws8S/MGGC+Tj8SNIJMymVDFgvMHhBQFrylr" +
    "rWdv///9v/YqMOEcZPBhFhmOKAYD//syxAYDyDQrAA5/ooD+BV9Bv+xYGErmBFDNRgA3RUY9+TVHQ7mShmKI+AekRmaFjYZbiGYU" +
    "BEYAgeIACRvWEcSB5x///6v///9QsRmeEBuqyeZaGDDgxZh1QnkarfwqHMeAyp0rn8iZ9cOWmH7DKBg64SsazElQyCwmIQBaMGUU" +
    "inX////9X//1VTDkIjFgFzIkFjNgNTXkqDzS1//7MMQJA8b0Kv4O/ySg7wVfwc/wUDQV3wk4XgROMkX5PjH8RJ0w38W4MEWBeDrh" +
    "H4Q7oWZKAlqOhJaxiUgGDjSCVMWIuIghgGC/JgAW+eZA4Uymwj3GZgvo9Ycmmpq15HTkCabJRlQUmLwgChSlG0dlUOnv//1qARYa" +
    "ednHPR9uuYM0DIGGxiCpobU3ab3qKmnSiL3xlPxBafc8ef/7MsQSg8dsLPwN/6Kg+oVewc/sWLNS2SGkYNDWYJh4YBA+FwKUXb9i" +
    "sKvGVjGZdPxnpamw44YLoEGmHTizBq2VrgdkuUpHrhzPhovZXsYQYPlgAInO1TjMgEiFk4GTu5GKfX//9X+u/+syIzMbTjGIEx/m" +
    "MAuB4zATRfAwSf2GMdZCbDZYtacysgJRMQKA9zBewB44kFAwIwllT+3/+zLEGYPHlCr6Df9iwOyFn0Hf7JSsbXP//6v///9RgWA5" +
    "h8HhjyO5mcaBrewJ417RoC8X8bpwTGGMubLhi74y2YPGK0GBKAnw37m9BJoYEDkkiHkRGQPTKsYw7DIxMDcxxEoyyIE09RA7C20z" +
    "k9+LN4GGQzeQ5s0xS0dCMIiDWDBKQio/TJN3aDQDkyEcMIBV1Oyy5+bRhJUKqZik//syxCGDx5Qs+g7/ZKDjhZ+Bv+hcUZz1mA0A" +
    "3hgYYmuYWRZimBZDWpvjAyMZGEMkmFvgoRgfQE6eyMYVGQDioDVQaW/cHUfKDgtMOQFMaAwMuR1NYkQPWeJNOaqITjrQXY6VG4WM" +
    "49IDjCfxiUwUQH/OtcMGVRAZm+kbp7Hf////X//9ZiMGZjOFBk0GZniMRs8gZ779RoslQwci+P/7MMQqg8eMKvQO/0SA74Vegd/k" +
    "kH7mpJfcJlcgXIYesL7mCZg2Iz8CvyagrJRIV24ccu///1f66jDikQpQNfzFNYwDkGhMCAEmDC2aqQwRchqM0smgDCFRTs2vYDOx" +
    "1N8kozcKTHISMOAMOCSzHgfWNYkQfmKASGR4umdRVGzagnuGlGiywVhwQAY8cxXERmRTkBxh6weEYNmE7P/7MsQxg8c0LPoN/4Kg" +
    "7oWegd/slGbbpm7kZAgmGkQIC1HnNX9At+oztGM8YTTZA37rMD7BujCiBNMz1+lDOA6HoTq8D+0zPQk/MKBF2jAeAVo+wsINpoML" +
    "bpDcvor///9ZjZcYclmCvwI4xwHcMBPF2zEZPNMwCsL9N8DvgDLlxHg+NLc1QEUWUQmDtVkLnLYW///2////7QEHBiv/+zLEOoPH" +
    "NCryDf9CwN2EnkG/9FCHpk4PxoCbZuAxB973JpgkEicaCU1mSse+ZkgAsUYQ8MbmBOg05/Q8HfQOiRJOJiAvWre2CZ0YXBeYchwY" +
    "oCqZBkgZ3JOcS8EZbc/xGxFjWRq5k28YRQLsmDjhVZgfQOGfPRG2KZnZYY4JgIOZK+zXYexqMAJQYlGPwZpG8YEODWmCGCWBiWdh" +
    "//syxEYDx0Qs8A7/ZKDwhZ6B3+yUIYpULuG79oZpj4YzAeUGKaRm0Ypi2MBcIAXFQGTdbhAkKoumD4BCxAGN4LmYAmGt5inuVUGo" +
    "Sw+ByowKadk9EcmcZEuZgrQ1EYHCD2HhhgZgRB1OHPikou6////9VTDsLDFQKzH8ODMQbzVNEjtb8TN+6fk3fYJQNkBzSDKuwJow" +
    "yESiMDwBdP/7MMROg8cMLPQN/6Kg6AVdgd/okDaRwsKQBqWMHa5DFPh///WYBg8Oh+YFDYYWl6YuLYZl/yYhZJRmI4jypiwsYyYc" +
    "wHpGoMOZVDRtAUmWwsYsA4OFQ0BV/vHAVL0HCaYpgWZGB0ZzjubKHQe3zOaNgzbnDGgFZw41SQYzQPRmHsh+Jg3wUKbTxGlOplqE" +
    "YoRmAhS8XmXrA14yQ//7MsRYg8dEKu4O/0SA44Wegd/wjBMjSDLG8026MCiBaTBtxAgyqSPiNblFfjhExNUyT8d6MKAEUTApwMkJ" +
    "JiIIgyns3GOUU9eVMAxANTAEwAUmAazA2gWYwUwH+MS+G+jI++cwyXA0kOlgl0TRDg/gxNgE9MKbAgDA9wRErAmTABAA8RgDBQAM" +
    "yREJhFf//+r////UAAkAAAzEqoH/+zLEYwPHgCzsDv9koNkFXcG/6FwrYMwJYcxl0MzATvbI2kcMQJxAApBTrWHUDAFrPgFgjySf" +
    "yeVgPwQUj3+CeIArJ6KRsbf+Og5mhpBsSpj/8440OH4Nmt5b//sNz9vNz7dqMbf//6e84ZBAYeER4RfUCA45tFQVUpbTpeHMXJzH" +
    "yIa0kpFxQlqOZVNpyjgUAosSo0jQlcHYifLH//syxG2ACVwq6hX2AAGwnCVXNrAAgaHnQaAQdKqPevWdEuJbv/UeI5ZMQU1FMy4x" +
    "MDBVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV" +
    "VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVf/7MMRWA8cAOO4c8wAAAAA0gAAABFVVVVVVVVVVVVVVVVVVVVVVVVVV" +
    "VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV" +
    "VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVQ==",
  "pulse":
    "SUQzBAAAAAAAIlRTU0UAAAAOAAADTGF2ZjYxLjEuMTAwAAAAAAAAAAAAAAD/+0DAAAAAAAAAAAAAAAAAAAAAAABJbmZvAAAADwAA" +
    "AAsAAAdyAC0tLS0tLS0tLUJCQkJCQkJCQldXV1dXV1dXV2xsbGxsbGxsbIGBgYGBgYGBgZaWlpaWlpaWlqurq6urq6urq8DAwMDA" +
    "wMDAwNXV1dXV1dXV1erq6urq6urq6v///////////wAAAABMYXZjNjEuMy4AAAAAAAAAAAAAAAAkAnYAAAAAAAAHcgQlTWIAAAAA" +
    "AP/7MMQAAAdARTpVlgAJFoypdzcgAgcAAuWXjQDoB0A6D7JxEEbDx+9nzecaYOLhTsO5Dj+AfBuJZPMzMzMz8wPFixYscAA8PDw9" +
    "IAAH/48AAAlICgUCgMAAAAAABCcYCBYSvVOYKiHVhwWVA8WETwGYxkIUXih3JS2eFdEEfAVkkSDfiMRZw5whN/kBHNGVJoi3wqCq" +
    "TKL9mAJADf/7MsQDg8hsLRQd9gAg3wWhQb/slJgFACOYB0ALGBAgUhgeIOEYTuEbGEaopBofhNYYQuB0GCUgRxgMQEOYCIAYmAdA" +
    "CpgBIAoEAAS/hSIpZsqmBAwxEhMmPDR2k3i0MDdBSzB9Aswx303OPkYCMDE8gWEwYsDGO8dTa0Qz4nMhDgUMreelrUO5VRGATCQe" +
    "MYkEysajRatNwRwwYUL/+zLECYPH5CsGDn9EgQ6FoEG/8JAVMMQFIDJ7YEk+QI8BMKQCEDAFwKcycgxSMAjgsBVWguTyGed/////" +
    "/u//9ag5hQUZGRmgIBtrWdpcGCbgvphFAkMYmP9LmnBsTpi7ImgYUYERnb5sbiYZpE+GWiWYvEAQCUqi4q1p3Z//9P+z//5NMAJA" +
    "ETAOwEUdALDAGAGYwRQEuAAH6YIK//syxAwACogtBhX8AAEQjqaDOzAAFUmNeksZit9EGfvKW9mYhjcpiP4fCYVuCHmAUAQBgXwH" +
    "QYFkAeGAAgDJgDIACFSpnpeQJs////2f///7IAEIAyhAWY0C4QEaYRQWd8giYbKiNzOZbmubLqsiNIVxxQxuBsw9BfIgZgBhAOv3" +
    "Th8AXXD5P8qjQIeV//L5w0CP4XNKBwAE9jCjDP/7MMQDg8h4SyxdpIAIAAAAAAAABKmjOmjLjEuzFIzcRzmSTPiAsRM0bMgDYgBQ" +
    "hhQCG0vRSIiZMKgBACBkmTISVmkQqFTMIKbBTgUVkMyCnxb/SaMKDIw6OjGIk/zGQMMyCowO7z1w7/waExoDiQwMGg78eshZKTC/" +
    "62dbOLl09//t/fqLD6N8Pl1B0tVBkMANi4qA0YD4BZggAf/7MsQlAAAAAaQUAAAg7YungzjwAAmCAICYzQqJjLeCmU7GWZxg+Ziq" +
    "BPmAyDAYK4IxgbgICAAcFACslDoAw7PeCsMaEIDAAQMHicxERjIKBNBOQ7HgzGWnv8+dcoJMX9CoDCEgU84ewjUB3Mxkgx0JzDoK" +
    "QtX0oK41nZ////sVTIMFEzHCwzlNNefjn9cwRgGQMJVDqTILigY9ssb/+zLESwPHdC8YHeYAKPKFoQHP8Mi4MPbAJzA/ADE8p42A" +
    "0y4AIGpdN5HJTTcSoMJDzICgz1HNmdjq8swSgGIMJDEGTGrJng2+9AmMF0CwzBAQRg5qVNdVjNDMxsYMGA2JOyy5+bR3XWZqmcJA" +
    "kHDIxoBArbTDE7Vw7rZCcMYsDozCWQbI6A+TYaaM9GMyWODEwVEgMqqiky2e2/////syxFKDxqgtCg3/RKDihaEBv+yU/7QUACGA" +
    "LACRgD4B2wkwJECJMCcBFjAKAKIw7ATSMSvUej8YA38yIgYSMQGDDDCKARILgTZgYIFyYEWAegwAiBQBgDEDRFh3Hf+X3IxYypKT" +
    "mdscCYgOA/PlHE//63f///11IAAQAYFIrPAAAAAdMwABIxYGwyEIZhhhKKhiemR+QD48Ohw4pf/7MMRfg8cYLQYOf4ZBgohhAr+A" +
    "AJj+TRheNiN0MmT4bmDoDmKYAGBwJ86DpJpVKaSV3Oecs6AtAFGwW6TEv//ASMHHGqp1utATXoe///2mVZfDmNaNS7VNwJceCpxu" +
    "yHG0GLCAMzCyIEwVjfcQoNGA5YDVGYOCAQMC5iwxFAUAEB4++Wl0BKEo++tWl3Llz0ioSIb3h0JMQU1FM//7MsRWAA2AeTGZ3QAA" +
    "7ApeA7LAAS4xMDBVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV" +
    "VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVX/+zLERoPA" +
    "AAGkAAAAIAAANIAAAARVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV" +
    "VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV",
};
